### ISSUE TITLE
QUESTION: Bank short names

### ISSUE THREAD

**Issue by micaiah-effiong** [BolajiOlajide/ng-banks#22]
How did you get the ```short``` names for the banks? What I found were ```swift code``` and did not match the initial ```bank short names```

**Comment by micaiah-effiong** [comment]
@BolajiOlajide can you respond to this

**Comment by BolajiOlajide** [comment]
The short names are unique to the library, so you can use your discretion to generate a three-digit code unique to each bank.

I'm sorry i somehow don't get notifications on issues except I'm mentioned

**Comment by BolajiOlajide** [comment]
Cc @micaiah-effiong

**Comment by micaiah-effiong** [comment]
> The short names are unique to the library, so you can use your discretion to generate a three-digit code unique to each bank.
> 
> I'm sorry i somehow don't get notifications on issues except I'm mentioned

Alright. I can work with that to make a `PR`.
