### ISSUE TITLE
Include CBN recognized bank code to Bank object

### ISSUE THREAD

**Issue by BolajiOlajide** [BolajiOlajide/ng-banks#6]
For the purpose of folks using `ng-banks` for processing payments, we'll need to make available the CBN-recognized code for transactions for each bank.

If you check this [link paystack](https://developers.paystack.co/v1.0/reference#list-banks) exposes an endpoint that can be used to get this code.
All you need to do is query that URL and get the CBN recognized code for each bank.

Once that is done, the structure of the banks will be like this:
```js
{ name: 'Bolaji Bank', code: 203, slug: 'BBK' }
```

**Comment by max-arias** [comment]
Hey @BolajiOlajide  I'd like to help, is it ok if I grab this? Thanks!

**Comment by BolajiOlajide** [comment]
Yes @BolajiOlajide Feel free to take it on.
